host = "chat.freenode.net"
port = 6667
tls = false
nick = "bncr-dev"
username = "bncr-dev"
password = ""

# Everything below is optional.

watchConfig = true

[channels."#developerslv"]
ops = [
  "daGrevis",
  "ij",
]
voiced = [
  "bncr",
  "msks",
  "zn",
  "Xn",
  "vdk",
  "agni",
  "snbt",
]
accounts = [
  ["ij", "sie"],
]
banAccountOnSpamJoin = { intervalSeconds = 60, maxJoins = 5 }
kickOnJoin = [
  "zandis",
]
kickIgnores = [
  "bncr",
  "msks",
  "zn",
  "Xn",
  "vdk",
  "agni",
  "snbt",
]
[channels."#developerslv".kickPatterns]
"*" = [
  "^!voteban",
  "^!echo",
]
acid3 = [
  "^\\){3,}",
]
dianshi = [
  ["666", "devils number!"],
  ["p..t..k"],
]
