host = 'chat.freenode.net'
port = 6667
tls = false
nick = 'bncr-dev'
username = 'bncr-dev'
password = ''

# Everything below is optional.

watchConfig = true

[channels."#developerslv"]
ops = [
  "daGrevis",
  "ij",
]
voiced = [
  "bncr",
  "msks",
  "zn",
  "Xn",
  "vdk",
  "agni",
  "snbt",
]
accounts = [
  ["ij", "sie"],
]
kickOnJoin = [
  "zandis",
]
kickIgnores = [
  "bncr",
  "msks",
  "zn",
  "Xn",
  "vdk",
  "agni",
  "snbt",
]
[channels."#developerslv".kickPatterns]
"*" = [
  "^!voteban",
  "^!echo",
  "^\\){3,}",
]
dianshi = [
  "pietiek",
]
